---
- name: Deploy admin user with SSH key and sudo privileges
  hosts: all
  become: yes
  vars:
    admin_user: admin
    admin_uid: 2000
    admin_shell: /bin/bash
    public_key_file: "~/.ssh/id_ed25519.pub"

  tasks:
    - name: Create admin group
      group:
        name: "{{ admin_user }}"
        state: present

    - name: Create admin user
      user:
        name: "{{ admin_user }}"
        group: "{{ admin_user }}"
        uid: "{{ admin_uid }}"
        shell: "{{ admin_shell }}"
        home: "/home/{{ admin_user }}"
        create_home: yes
        state: present
        system: no

    - name: Create .ssh directory for admin user
      file:
        path: "/home/{{ admin_user }}/.ssh"
        state: directory
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: '0700'
    - name: Deploy public key to authorized_keys
      copy:
        content: "{{ public_key_content.content | b64decode }}"
        dest: "/home/{{ username }}/.ssh/authorized_keys"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0600'

    - name: Ensure admin user has sudo privileges
      copy:
        content: "{{ admin_user }} ALL=(ALL) NOPASSWD:ALL"
        dest: "/etc/sudoers.d/{{ admin_user }}"
        mode: '0440'
        validate: 'visudo -cf %s'

    - name: Set admin user password (optional - change 'password123' to secure password)
      user:
        name: "{{ admin_user }}"
        password: "{{ 'password123' | password_hash('sha512') }}"
      when: false  # Set to true if you want to set a password

    - name: Verify admin user creation
      command: id "{{ admin_user }}"
      register: user_check
      changed_when: false

    - name: Display user creation status
      debug:
        msg: "Admin user {{ admin_user }} created successfully with UID {{ admin_uid }}"
      when: user_check.rc == 0